apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  apps: nginx-pod
spec:
 containers:
  - image: nginx
    name: nginx-pod
    ports:
     - containerPort: 80
       hostPort: 8080
       protocol: TCP
